In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,roc_auc_score,roc_curve
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier

In [2]:
class Model:
    def __init__(self,data):           # constructor
        self.df = pd.read_csv(data)    # self.df = instance variable
#         print(self.df.head())
        self.m1 = LogisticRegression(criteriom='gini',max_depth=4,min_samples_split=15)
        self.m2 = DecisionTreeClassifier
    
    
    

    
m1 = Model('iris.csv')


   sepal_length  sepal_width  petal_length  petal_width        label
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa


In [29]:
class Model:
    def __init__(self,data):                      # constructor
        self.df = pd.read_csv(data)               # self.df = instance varible 
#         print(self.df.head())
        self.m1 = LogisticRegression(max_iter=1000)
        self.m2 = DecisionTreeClassifier(criterion='gini',max_depth=4,min_samples_split=15)
        self.m3 = RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=4,
                                         min_samples_split=15)
        self.m4 = KNeighborsClassifier(n_neighbors=7)
        
    def select_model(self,model):
        self.mod_name = model
        if self.mod_name == 'LogReg':
            self.model = self.m1
        elif self.mod_name == 'DT':
            self.model = self.m2
        elif self.mod_name == 'RF':
            self.model = self.m3
        elif self.mod_name == 'KNN':
            self.model = self.m4
            
    def split(self,ts,rs):
        self.ts,self.rs=ts,rs
        self.x = self.df.iloc[:,:-1]
        self.y = self.df.iloc[:,-1]
        self.x_train,self.x_test,self.y_train,self.y_test = train_test_split(self.x,self.y,
                                                                             test_size=self.ts,
                                                                            random_state=self.rs)        
        print('x_train shape',self.x_train.shape)
        print('x_test shape',self.x_test.shape)
        print('y_train shape',self.y_train.shape)
        print('y_test shape',self.y_test.shape)
            
    def fit(self):
        self.model.fit(self.x_train,self.y_train)
    
    def predict_and_metrics(self):
        self.ypred = self.model(self.x_test)
        self.train_sc = self.model.score(self.x_train,self.y_train)
        self.test_sc = self.model.score(self.x_test,self.y_test)
#     print('training score',self.train_sc)
#     print('testing score',self.tet_sc)
        self.acc_sc = accuracy_score(self.y_test,self.ypred)
        self.cm = confusion_matrix(self.y_test,self.ypred)
        self.creport = classification_report(self.y_test,self.ypred)
        return self.ypred,self.train_sc,self.test_sc,self.acc_sc,self.cm,self.creport
        
    

        
a1 = Model('iris.csv')
a1.split(ts=0.25,rs=32)
a1.select_model('LogReg')
a1.fit()

# ypred,train_sc,test_sc,acc_sc,cm,creport = predict_and_metrics()

# print('ypred:',ypred)
# print()

x_train shape (111, 4)
x_test shape (38, 4)
y_train shape (111,)
y_test shape (38,)


In [24]:
class Model:
    def __init__(self,data):                      # constructor
        self.df = pd.read_csv(data)               # self.df = instance varible 
#         print(self.df.head())
        self.m1 = LogisticRegression(max_iter=1000)
        self.m2 = DecisionTreeClassifier(criterion='gini',max_depth=4,min_samples_split=15)
        self.m3 = RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=4,
                                         min_samples_split=15)
        self.m4 = KNeighborsClassifier(n_neighbors=7)
        
    def select_model(self,model):
        self.mod_name = model                          # self.mod_name = instance_variable
        if self.mod_name == 'LogReg':
            self.model = self.m1                       # self.model = instance variable
        elif self.mod_name == 'DT':
            self.model = self.m2
        elif self.mod_name == 'RF':
            self.model = self.m3
        elif self.mod_name == 'KNN':
            self.model = self.m4
        print(self.model)
        
    
    def split(self,ts,rs):   # ts=test_size,rs=random_state
        self.ts,self.rs = ts,rs
        self.x = self.df.iloc[:,:-1]
        self.y = self.df.iloc[:,-1]
        self.x_train,self.x_test,self.y_train,self.y_test = train_test_split(self.x,self.y,
                                                                             test_size=self.ts,
                                                                            random_state=self.rs)
        print('x_train shape',self.x_train.shape)
        print('x_test shape',self.x_test.shape)
        print('y_train shape',self.y_train.shape)
        print('y_test shape',self.y_test.shape)
        
    
    def fit(self):
        self.model.fit(self.x_train,self.y_train)
        
    def predict_and_metrics(self):
        self.ypred = self.model.predict(self.x_test)
        self.train_sc = self.model.score(self.x_train,self.y_train)
        self.test_sc = self.model.score(self.x_test,self.y_test)
        self.acc_sc = accuracy_score(self.y_test,self.ypred)
        self.cm = confusion_matrix(self.y_test,self.ypred)
        self.creport = classification_report(self.y_test,self.ypred)
        return self.ypred,self.train_sc,self.test_sc,self.acc_sc,self.cm,self.creport

        
a1 = Model('iris.csv')
a1.split(ts=0.25,rs=32)  # ts = test_size,rs=random_state
a1.select_model('LogReg')
a1.fit()
ypred,train_score,test_score,acc_score,cm,creport = a1.predict_and_metrics()
print('Predictions\n',ypred)
print('Train_score',train_score)
print('Test_score',test_score)
print('Accuracy_Score',acc_score)
print('Confusion_Matrix\n',cm)
print('Classification_report\n',creport)


x_train shape (111, 4)
x_test shape (38, 4)
y_train shape (111,)
y_test shape (38,)
LogisticRegression(max_iter=1000)
Predictions
 ['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica']
Train_score 0.990990990990991
Test_score 0.9473684210526315
Accuracy_Score 0.9473684210526315
Confusion_Matrix
 [[16  0  0]
 [ 0  9  2]
 [ 0  0 11]]
Classification_report
                  precision    recall  f1-score   support

    Iris-setosa      

In [25]:
a2 = Model('iris.csv')
a2.split(ts=0.25,rs=32)  # ts = test_size,rs=random_state
a2.select_model('DT')
a2.fit()
ypred,train_score,test_score,acc_score,cm,creport = a2.predict_and_metrics()
print('Predictions\n',ypred)
print('Train_score',train_score)
print('Test_score',test_score)
print('Accuracy_Score',acc_score)
print('Confusion_Matrix\n',cm)
print('Classification_report\n',creport)


x_train shape (111, 4)
x_test shape (38, 4)
y_train shape (111,)
y_test shape (38,)
DecisionTreeClassifier(max_depth=4, min_samples_split=15)
Predictions
 ['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica']
Train_score 0.990990990990991
Test_score 0.9473684210526315
Accuracy_Score 0.9473684210526315
Confusion_Matrix
 [[16  0  0]
 [ 0  9  2]
 [ 0  0 11]]
Classification_report
                  precision    recall  f1-score   suppor

In [26]:
a1 = Model('iris.csv')
a1.split(ts=0.25,rs=32)  # ts = test_size,rs=random_state
a1.select_model('KNN')
a1.fit()
ypred,train_score,test_score,acc_score,cm,creport = a1.predict_and_metrics()
print('Predictions\n',ypred)
print('Train_score',train_score)
print('Test_score',test_score)
print('Accuracy_Score',acc_score)
print('Confusion_Matrix\n',cm)
print('Classification_report\n',creport)


x_train shape (111, 4)
x_test shape (38, 4)
y_train shape (111,)
y_test shape (38,)
KNeighborsClassifier(n_neighbors=7)
Predictions
 ['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica']
Train_score 0.972972972972973
Test_score 0.9473684210526315
Accuracy_Score 0.9473684210526315
Confusion_Matrix
 [[16  0  0]
 [ 0  9  2]
 [ 0  0 11]]
Classification_report
                  precision    recall  f1-score   support

    Iris-setosa    

#### passing target variable in split to make it more user friendly/generilsed model

In [31]:
class Model:
    def __init__(self,data):                      # constructor
        self.df = pd.read_csv(data)               # self.df = instance varible 
#         print(self.df.head())
        self.m1 = LogisticRegression(max_iter=1000)
        self.m2 = DecisionTreeClassifier(criterion='gini',max_depth=4,min_samples_split=15)
        self.m3 = RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=4,
                                         min_samples_split=15)
        self.m4 = KNeighborsClassifier(n_neighbors=7)
        
    def select_model(self,model):
        self.mod_name = model                          # self.mod_name = instance_variable
        if self.mod_name == 'LogReg':
            self.model = self.m1                       # self.model = instance variable
        elif self.mod_name == 'DT':
            self.model = self.m2
        elif self.mod_name == 'RF':
            self.model = self.m3
        elif self.mod_name == 'KNN':
            self.model = self.m4
        print(self.model)
        
    
    def split(self,ts,rs,tar_var):   # ts=test_size,rs=random_state
        self.ts,self.rs = ts,rs
        self.tar_var = tar_var
        self.x = self.df.drop(self.tar_var,axis=1)
        self.y = self.df[self.tar_var]
        self.x_train,self.x_test,self.y_train,self.y_test = train_test_split(self.x,self.y,
                                                                             test_size=self.ts,
                                                                            random_state=self.rs)
        print('x_train shape',self.x_train.shape)
        print('x_test shape',self.x_test.shape)
        print('y_train shape',self.y_train.shape)
        print('y_test shape',self.y_test.shape)
        
    
    def fit(self):
        self.model.fit(self.x_train,self.y_train)
        
    def predict_and_metrics(self):
        self.ypred = self.model.predict(self.x_test)
        self.train_sc = self.model.score(self.x_train,self.y_train)
        self.test_sc = self.model.score(self.x_test,self.y_test)
        self.acc_sc = accuracy_score(self.y_test,self.ypred)
        self.cm = confusion_matrix(self.y_test,self.ypred)
        self.creport = classification_report(self.y_test,self.ypred)
        return self.ypred,self.train_sc,self.test_sc,self.acc_sc,self.cm,self.creport

        
a1 = Model('iris.csv')
a1.split(ts=0.25,rs=32,tar_var='label')  # ts = test_size,rs=random_state
a1.select_model('LogReg')
a1.fit()
ypred,train_score,test_score,acc_score,cm,creport = a1.predict_and_metrics()
print('Predictions\n',ypred)
print('Train_score',train_score)
print('Test_score',test_score)
print('Accuracy_Score',acc_score)
print('Confusion_Matrix\n',cm)
print('Classification_report\n',creport)


x_train shape (111, 4)
x_test shape (38, 4)
y_train shape (111,)
y_test shape (38,)
LogisticRegression(max_iter=1000)
Predictions
 ['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica']
Train_score 0.990990990990991
Test_score 0.9473684210526315
Accuracy_Score 0.9473684210526315
Confusion_Matrix
 [[16  0  0]
 [ 0  9  2]
 [ 0  0 11]]
Classification_report
                  precision    recall  f1-score   support

    Iris-setosa      

#### modiffications : null value handling, col drop, label encoding

In [50]:
class Model:
    def __init__(self,data):                      # constructor
        self.df = pd.read_csv(data)               # self.df = instance varible 
#         print(self.df.head())
        self.m1 = LogisticRegression(max_iter=1000)
        self.m2 = DecisionTreeClassifier(criterion='gini',max_depth=4,min_samples_split=15)
        self.m3 = RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=4,
                                         min_samples_split=15)
        self.m4 = KNeighborsClassifier(n_neighbors=7)
        
    def select_model(self,model):
        self.mod_name = model                          # self.mod_name = instance_variable
        if self.mod_name == 'LogReg':
            self.model = self.m1                       # self.model = instance variable
        elif self.mod_name == 'DT':
            self.model = self.m2
        elif self.mod_name == 'RF':
            self.model = self.m3
        elif self.mod_name == 'KNN':
            self.model = self.m4
        print(self.model)
        
    def handle_null(self):
        self.cat_nan = [i for i in self.df.columns if self.df[i].isnull().sum()>0 and self.df[i].dtypes=='object']
        self.num_nan = [i for i in self.df.columns if self.df[i].isnull().sum()>0 and self.df[i].dtypes!='object']
        for i in self.cat_nan:
            z1 = self.df[i].mode().max()
            self.df[i].fillna(z1,inplace=True)
        for i in self.num_nan:
            z2 = self.df[i].mean()
            self.df[i].fillna(z2,inplace=True)
        print(self.df.isnull().sum())
        
    
    
    def drop_cols(self,*col_list):
        self.clist = col_list # this will be of typetuple but in below func we need o convert it into lisrt
        self.df.drop(list(self.clist),axis=1,inplace=True)
        print(self.df.head())
    
    def cat_encode(self):
        self.cat_cols = [i for i in self.df.columns if self.df[i].dtypes=='object']
        print('cat cols',self.cat_cols)
        self.lb = LabelEncoder()
        for i in self.cat_cols:
            self.df[i] = self.lb.fit_transform(self.df[i])
        print(self.df.head())
        
        
    
    
    
    def split(self,ts,rs,tar_var):   # ts=test_size,rs=random_state
        self.ts,self.rs = ts,rs
        self.tar_var = tar_var
        self.x = self.df.drop(self.tar_var,axis=1)
        self.y = self.df[self.tar_var]
        self.x_train,self.x_test,self.y_train,self.y_test = train_test_split(self.x,self.y,
                                                                             test_size=self.ts,
                                                                            random_state=self.rs)
        print('x_train shape',self.x_train.shape)
        print('x_test shape',self.x_test.shape)
        print('y_train shape',self.y_train.shape)
        print('y_test shape',self.y_test.shape)
        
    
    def fit(self):
        self.model.fit(self.x_train,self.y_train)
        
    def predict_and_metrics(self):
        self.ypred = self.model.predict(self.x_test)
        self.train_sc = self.model.score(self.x_train,self.y_train)
        self.test_sc = self.model.score(self.x_test,self.y_test)
        self.acc_sc = accuracy_score(self.y_test,self.ypred)
        self.cm = confusion_matrix(self.y_test,self.ypred)
        self.creport = classification_report(self.y_test,self.ypred)
        return self.ypred,self.train_sc,self.test_sc,self.acc_sc,self.cm,self.creport

        
a1 = Model('titanic_train.csv')
a1.handle_null()
a1.cat_encode()
# a1.drop_cols('PassengerId','Name','Ticket','Cabin')
# a1.split(ts=0.25,rs=32,tar_var='Survived')  # ts = test_size,rs=random_state
# a1.select_model('LogReg')
# a1.fit()
# ypred,train_score,test_score,acc_score,cm,creport = a1.predict_and_metrics()
# print('Predictions\n',ypred)
# print('Train_score',train_score)
# print('Test_score',test_score)
# print('Accuracy_Score',acc_score)
# print('Confusion_Matrix\n',cm)
# print('Classification_report\n',creport)


PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64
cat cols ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']
   PassengerId  Survived  Pclass  Name  Sex   Age  SibSp  Parch  Ticket  \
0            1         0       3   108    1  22.0      1      0     523   
1            2         1       1   190    0  38.0      1      0     596   
2            3         1       3   353    0  26.0      0      0     669   
3            4         1       1   272    0  35.0      1      0      49   
4            5         0       3    15    1  35.0      0      0     472   

      Fare  Cabin  Embarked  
0   7.2500    145         2  
1  71.2833     81         0  
2   7.9250    145         2  
3  53.1000     55         2  
4   8.0500    145         2  
